### ISSUE TITLE
`INTEGERLITERAL` somehow doesn't include `-`?

### ISSUE THREAD

**Issue by sancarn** [Beakerboy/VBA-Linter#76]
@Beakerboy added the linter to stdVBA last night. Something I don't fully understand is the following:

```
stdArray.cls:184:33: F999 extraneous input '-' expecting {'EMPTY', 'FALSE', 'NOTHING', 'NULL', 'TRUE', STRINGLITERAL, OCTLITERAL, HEXLITERAL, INTEGERLITERAL, FLOATLITERAL, DATELITERAL}
```

Specific code line:

```vb
Attribute NewEnum.VB_UserMemId = -4
```

So as far as I know this is complaining about the `-` in `-4`. But what i don't understand is this is an `INTEGERLITERAL` right? At least according to the [grammar](https://github.com/Beakerboy/grammars-v4/blob/master/vba/vba.g4#L2170-L2176):

```antlr
SHORTLITERAL
    : (PLUS | MINUS)? DIGIT+
    ;

INTEGERLITERAL
    : SHORTLITERAL ('E' SHORTLITERAL)?
    ;

MINUS
    : '-'
    ;

fragment DIGIT
    : [0-9]
    ;
```

Maybe I'm missing something here, but it looks like this complies with the rules perfectly?

**Comment by Beakerboy** [comment]
You are looking at the vba6 grammar. I’ve rewritten it using the MS-VBAL document from Microsoft and targeting VBA 7.1. The grammar that they use recommends just saving digits to the literal and then perform a unary minus operation on them. I think this has already been fixed.

**Comment by Beakerboy** [comment]
In case you are interested, here are the updated grammars
https://github.com/Beakerboy/grammars-v4/tree/coverage/vba
I have a separate file for the conditional-compilation grammar, so I can actually precompiler before Linting. I also have a LIKE pattern, so I can translate that to python regex syntax in case anyone uses a like operation in their conditional compilation tests…that’s a work in progress.

**Comment by sancarn** [comment]
Cool thanks, FYI in the past I found out that this:

`[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*`

Appears to be the regex for identifiers (variables/function names and type names)

**Comment by Beakerboy** [comment]
Thanks for that. I can use that in my Linting tool. The MA-VBAL has a section on international character sets that I’ve not looked at.
