### ISSUE TITLE
E220 Keyword not capitalized - False flag for PtrSafe?

### ISSUE THREAD

**Issue by DecimalTurn** [Beakerboy/VBA-Linter#87]
I tried to run the dev version of the linter on the dev branch of one of my repos [here](https://github.com/DecimalTurn/Excel-Pomodoro-Timer/actions/runs/8240485163/job/22535963036). 

It looks like the E220 falsly flags the keyword `PtrSafe` as not being correctly capitalized in this line of this [file](https://github.com/DecimalTurn/Excel-Pomodoro-Timer/blob/fd52e2f1bde825389a51346d57e287beb94fe9e9/src/Pomodoro_Timer.xlsb/winWorkArea.bas#L10) (10,21):
```
    Private Declare PtrSafe Function SystemParametersInfo Lib "user32" _
```

**Comment by Beakerboy** [comment]
Fixed in dev. Thanks for testing and for the feedback!

**Comment by DecimalTurn** [comment]
Great, thanks! I was thinking of making another issue for that, but you're too quick 😅.

**Comment by DecimalTurn** [comment]
`LongPtr` (and potentially `LongLong`) seems to be causing some issues as well.

**Comment by Beakerboy** [comment]
Thanks. Fixed
